### ISSUE TITLE
안녕하세요.

### ISSUE THREAD

**Issue by GwADSD** [jhleekr/kakao.py#1]
혹시 오픈채팅 광고 채팅내용 가리기 및 강퇴&신고하기 기능 만들어주실 수 있나요??
text = ["광고내용","광고","광고1"]
오픈채팅에서 작성된 내용이 text중 하나라도 포함이 되면 채팅내용 가리기 및 강퇴&신고하고 내보내기 봇을 만들고 싶어서요.!
답변주시면 감사드리겠습니다.

**Comment by jhleekr** [comment]
안녕하십니까 :)
현재 가리기를 하는 동시에 신고를 하는 기능은 구현되어있지 않지만, 채팅내용 가리기 및 강퇴 기능은 아래의 방법으로 사용이 가능합니다. (봇 계정에 관련 권한이 부여된 상태여야 합니다)
```py
await chat.hide() # 해당 채팅을 가리기합니다.
await chat.kick() # 해당 메시지의 작성자를 강퇴합니다.
```
또한 Bot을 이용하실 때에는 chat대신 ctx를 사용하셔도 가능합니다.
세부적인 함수에 대한 설명이 없었던 점 사과드리며, 빠른 시일 내에 관련 내용을 정리할 수 있도록 하겠습니다.
혹시 추가적인 문의가 있으신 경우, 새 issue를 열어주시거나 이메일을 통해 문의해주세요. 감사합니다!

**Comment by GwADSD** [comment]
상세한 설명감사드립니다. 아뇨아뇨 이렇게 공개해주는 것만으로도 정말 감사드립니다.
지금 필터 넣고 테스트하면서 거의 다 완성했는데,
로그인 하고, 로그아웃하고 반복 여러번 하니까 status -100 으로 계속 와서 잠시 차단된 것 같습니다.
예전에 옛날버전 썻었는데 똑같은 현상으로 하루정도 차단당한 경우가 있어서..
좋은 자료 올려주셔서 대단히 감사드립니다!!
좋은 하루 보내세요!

**Comment by GwADSD** [comment]
안녕하세요.
올려진 자료중에 기본적으로 ping 쓰면 답장(reply)로 pong 이 채팅에 쳐지는데요.
그냥 답장말고 chat 써지는 건 안되나요..? sendText 나 sendChat 함수 이용하면되는건가요?
그리고 명령어를 만들고 싶은데, 예를 들어 
!오늘날씨 라고 입력하면, 날씨API 를 가져와서 오늘날씨를 알려주는 걸 만들고싶은데,
quickstart-bot 부분 고치면 되는건가요?ㅎㅎ

**Comment by jhleekr** [comment]
> 안녕하세요.
> 올려진 자료중에 기본적으로 ping 쓰면 답장(reply)로 pong 이 채팅에 쳐지는데요.
> 그냥 답장말고 chat 써지는 건 안되나요..? sendText 나 sendChat 함수 이용하면되는건가요?
> 그리고 명령어를 만들고 싶은데, 예를 들어
> !오늘날씨 라고 입력하면, 날씨API 를 가져와서 오늘날씨를 알려주는 걸 만들고싶은데,
> quickstart-bot 부분 고치면 되는건가요?ㅎㅎ

답변이 늦어 죄송합니다 (__)
해당 chat이 온 채널에 답장이 아닌 일반 채팅을 보내려면 sendText()를 활용하시면 됩니다 :)
명령어를 만들고 싶으신 경우에는 Bot을 활용하면 편하게 개발하실 수 있습니다. !오늘날씨 라는 명령어를 입력했을 때 처리하려면 다음과 같이 코드를 작성하시면 됩니다.
```py
import kakao
from kakao.ext import commands
from kakao.ext.commands import Bot


@commands.command(name="오늘날씨")
async def weather_today(ctx):
    #do something
    pass


kakao.check_reg("LoginId", "LoginPw")
bot = Bot("!", LoginId="LoginId", LoginPw="LoginPw")
bot.add_command(ping)
bot.run()
```

**Comment by GwADSD** [comment]
안녕하세요.
위에 답변대로 봤는데요. 
오픈채팅 단톡방에 적용하려고 하는데,
sendChat 이나 sendText를 사용하면, channelID가 있어야하는데 이건 어떻게 알아낼수 있나요??
sendChat 쓰면 이런 에러가 납니다.
AttributeError: 'Channel' object has no attribute 'sendText'
reply 말고 "오늘날씨" 라는 글자를 발견하면, 그냥 모든 채팅방중에서 "오늘날씨" 라고 입력한 채팅방이 있으면 해당 방에 채팅으로 보내주고 싶은데....

그리고 on_message(self) 말고, 제가 따로 만든 def 함수를 쓰레드로 실행중인데요.
특정 시점이 되면, 특정 오픈채팅방으로 메시지를 보내주고 싶은데 이건 어떻게 하나요..?

너무 질문이 많아서 죄송해요ㅠ

**Comment by jhleekr** [comment]
> 안녕하세요.
> 위에 답변대로 봤는데요.
> 오픈채팅 단톡방에 적용하려고 하는데,
> sendChat 이나 sendText를 사용하면, channelID가 있어야하는데 이건 어떻게 알아낼수 있나요??
> sendChat 쓰면 이런 에러가 납니다.
> AttributeError: 'Channel' object has no attribute 'sendText'
> reply 말고 "오늘날씨" 라는 글자를 발견하면, 그냥 해당 오픈채팅/옾챗이 아닌 1:1 채팅방에 채팅으로 보내주고 싶은데....
> 
> 그리고 on_message(self) 말고, 제가 따로 만든 def 함수를 쓰레드로 실행중인데요.
> 특정 시점이 되면, 오픈채팅방으로 메시지를 보내주고 싶은데 이건 어떻게 하나요..?
> 
> 너무 질문이 많아서 죄송해요ㅠ

```py
    chat.sendText("something")
    # or
    ctx.sendText("something")
```
위와 같이 수신된 message에서 sendText를 사용하시면 채널 ID 없이도 해당 채널로 메시지를 전송할 수 있습니다 :)

다만 현재 특정 시점마다 함수를 호출하는 등의 기능은 구현되어있지 않은 상태입니다. 해당 기능을 원하시면 채널 ID, 혹은 유저 ID 등을 저장해놓았다가 별도의 함수를 통해 특정 시점에 저장된 채널로 전송해야 합니다. 이 부분 도움드리지 못하는 점 죄송합니다 :(
