### ISSUE TITLE
kakao.py 질문

### ISSUE THREAD

**Issue by GwADSD** [jhleekr/kakao.py#2]
안녕하세요.
kakao.py에 대해서 궁금한 점이 있어서 질문드립니다.
1.
혹시, 카카오톡 오픈채팅 channel id값을 어떻게 구할 수 있나요..?
처음에 로그인 성공하면, 채팅목록(채팅방이름,채팅방 ID) 리스트 값을 얻고 싶습니다.
2.
명령어 등록을 통해, 답장주는 것은 가능한데, 아래와 같은 것을 하고싶습니다.
쓰레드나 스케줄링을 통하여, 특정 조건에 해당하면, 채팅방 ID 값을 이용해서, 특정 채팅방에 text를 보내고 싶습니다..
답변주시면 정말 감사드리겠습니다ㅠ.ㅠ

**Comment by jhleekr** [comment]
1. 해당 채팅방에서 메시지가 왔을 때 channel class를 활용하여 구할 수 있을 것으로 보입니다.
2. asyncio를 활용하시면 가능할 것으로 보입니다.
답변이 늦은 점 죄송합니다 ㅠㅠ
