### ISSUE TITLE
Exception: {'status': -999, 'message': '최신버전으로 업데이트가 필요합니다.'} 오류가 뜨면서 작동을 안합니다.

### ISSUE THREAD

**Issue by minsuho** [jhleekr/kakao.py#3]
Exception: {'status': -999, 'message': '최신버전으로 업데이트가 필요합니다.'} 오류가 뜨면서 작동을 안합니다.

future: <Task finished name='Task-1' coro=<Client.__login() done, defined at d:\KakaoBot-master\kakaopy\client.py:181> exception=Exception("{'status': -999, 'message': '최신버전으로 업데이트가 필요합니다.'}")>
Traceback (most recent call last):
  File "d:\KakaoBot-master\kakaopy\client.py", line 196, in __login
    raise Exception(str(r))
Exception: {'status': -999, 'message': '최신버전으로 업데이트가 필요합니다.'}

**Comment by jhleekr** [comment]
카카오톡 최소 지원버전 상향으로 인하여 문제가 발생하였으며, 문제되는 부분 수정하였습니다. [pypi](https://pypi.org/project/kakao.py/0.2.3/) 버전 또한 업데이트하였으니, 새 버전인 0.2.3을 이용해주시면 감사드리겠습니다 :)

**Comment by jhleekr** [comment]
봇 시작 전 자동으로 공지사항 홈페이지에서 버전 정보를 불러오는 기능을 추가했습니다! ([해당 커밋](https://github.com/jhleekr/kakao.py/commit/52d13f96b94d30ad31ca0bae78c551a99841788c)) 또한, [새 버전](https://pypi.org/project/kakao.py/0.3.0/)인 0.3.0을 이용해주시면 감사드리겠습니다

**Comment by minsuho** [comment]
감사합니다.

**Comment by minsuho** [comment]
혹시 코드로 오픈채팅방 들어가기 가능할까요?

**Comment by minsuho** [comment]
Failed to login. Will retry in 10 seconds. 뜨면서 로그인이 안됨니다.
