### ISSUE TITLE
로그인이 안됨니다.

### ISSUE THREAD

**Issue by minsuho** [jhleekr/kakao.py#5]
Failed to login. Will retry in 10 seconds 뜨면서 로그인이 안됨니다.  기기보안인증 했는데도 로그인이 안됨니다.
그리고 기기 이름 변경 할 수 있게 바꿔 주실 수 있나요?

**Comment by lmj806211** [comment]
checkIn의 Packet 부분 userId 만 수정하심됩니다.
kakao.py 에서 얻어오실 수 있고요.

개발자님께서 이정도는 연구해보라고 퀴즈를 내신거같기도...

**Comment by minsuho** [comment]
로그인 됨니다. 감사합니다.

**Comment by lmj806211** [comment]
넵 혹시 디스코드나 텔레하시면 아이디 부탁가능할까요 저도 이쪽 연구중인데 같이 함 연구해보고 싶어서요.

**Comment by jhleekr** [comment]
> checkIn의 Packet 부분 userId 만 수정하심됩니다. kakao.py 에서 얻어오실 수 있고요.
> 
> 개발자님께서 이정도는 연구해보라고 퀴즈를 내신거같기도...

제가 바쁘다 보니 여기에 신경을 많이 쓰지 못하고 있네요 ㅜㅜ
기기 이름 변경하는 기능 포함하여 시간 날 때 수정해보도록 하겠습니다
관심 가져주셔서 감사합니다 :)
