### ISSUE TITLE
영구정지 문제.

### ISSUE THREAD

**Issue by holiday22** [jhleekr/kakao.py#7]
안녕하세요.  선생님 코드를 참고해서 개인적인 봇을 운영중입니다.

로그인과 운영까지 성공하고 나서 메시지 가리기 기능을 이용중에 있습니다만.

주말에서 월요일로 넘어오면서 봇으로 사용한 아이디가 영구정지를 당하고 있습니다.

이 문제는 8월 29일 패치와 무관하게 가리기 로직의 문제일까요? 패치 전에는 영구정지가 없었습니다.

성공적으로 가리기 기능 이용하고 계시는 분들 가능하다면 코드 힌트 부탁드립니다.

**Comment by jhleekr** [comment]
kakao.py를 사용하며 단기간에 너무 많은 메시지를 전송하는 등의 정상적인 사용자의 활동으로 보기 힘든 활동이 확인되는 경우 정지되는 것으로 보이나, 카카오톡의 자세한 정지 조건은 알 수 없습니다 ㅜㅜ
본 라이브러리는 카카오와는 관련이 없는 라이브러리로, 카카오톡의 운영정책 상 문제가 있다면 언제든 정지가 될 수 있으므로 중요한 프로젝트에는 사용하지 않는 것을 추천드립니다
